### ISSUE TITLE
Why effect returns previous value

### ISSUE THREAD

**Issue by minogin** [stupidawesome/ng-effects#8] opened 2020-04-20 20:02 UTC
I have another question. Could you please apply attached patch to https://github.com/stupidawesome/debug-ng-effects repo?
When I click on the button I change the `@Input()` parameter value. But effected target always returns previous value not the one which was passed as a parameter.
Is it expected behaviour? Why is it happening?
[Target_returns_previous_value.zip](https://github.com/stupidawesome/ng-effects/files/4505856/Target_returns_previous_value.zip)

**Comment by stupidawesome** [comment] 2020-04-21 01:18
@minogin Thank you for raising this. I've confirmed this is a bug and will push an update shortly!

For background, ng-effects taps into the `RendererFactory` hooks to schedule effects to run. The problem is that inputs aren't yet updated when `begin` is being called, causing this issue. Subsequent change detection cycles were masking this issue in my tests. I've changed it now so that state is checked during the `ngDoCheck` lifecycle instead which should be much more robust, although it's using a private API that will need to be monitored for breaking changes going forward.

This update will land in 9.0.7. Edit: 9.0.7 is up.

The interop between ng-effects and imperative style is not perfect. For this fix to work something needs to import the `ViewRenderer` so it can patch the Renderer. I'll address this in the future but for now please take a look at the [debug repo]().

```ts
/** Workaround to trigger ViewRenderer before any components are loaded.
@NgModule({
    providers: [Effects]
})
export class AppModule {
    constructor(connect: Connect) {
        connect(this)
    }
}
```

**Comment by stupidawesome** [comment] 2020-04-21 13:09
In future versions I will rework this lib using base classes to provide connectable components. This will be a breaking change.

**Comment by stupidawesome** [comment] 2020-06-10 06:58
Closing as resolved, please reopen if there is still an issue.

**Closed as completed by stupidawesome** 2020-06-10 06:58 UTC
